name: Deploy to Google App Engine

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Github Action
      uses: actions/checkout@v4

    - name: Set up JAVA 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean package

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Deploy to Production in App Engine
      uses: google-github-actions/deploy-appengine@v2
      with:
        deliverables: app.yml
